services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - uploads_data:/app/uploads
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=postgis
      - DB_PORT=5432
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET}
      - FILE_DRIVER=${FILE_DRIVER}
      - TYPESENSE_HOST=${TYPESENSE_HOST}
      - TYPESENSE_PORT=${TYPESENSE_PORT}
      - TYPESENSE_PROTOCOL=${TYPESENSE_PROTOCOL}
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
    depends_on:
      - postgis
      - redis

  postgis:
    image: postgis/postgis:latest
    mem_limit: 216M
    cpus: "0.15"
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - '225immo_backend:/var/lib/postgresql/data:rw'
  
  redis:
    image: redis:latest

  typesense:
    image: typesense/typesense:28.0
    restart: on-failure
    volumes:
      - typesense-data:/data
    command: '--data-dir /data --api-key=xyz --enable-cors'

volumes:
  225immo_backend:
  uploads_data:
  typesense-data: