services:
  postgis:
    image: postgis/postgis:latest
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - '225immo_backend:/var/lib/postgresql/data:rw'
  
  redis:
    image: redis:latest
    ports:
      - '6379:6379'


  typesense:
    image: typesense/typesense:28.0
    restart: on-failure
    ports:
      - '8108:8108'
    volumes:
      - typesense-data:/data
    command: '--data-dir /data --api-key=xyz --enable-cors'

volumes:
  225immo_backend:
  uploads_data:
  typesense-data:
