name: Deploy to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Source profile to load nvm, bun, and other environment settings
            source ~/.bashrc
            cd ${{ secrets.VPS_DEPLOY_PATH }}
            git pull origin main
            docker compose down
            docker compose build --pull --no-cache
            docker compose up -d
            # Add a sleep to wait for services to be ready
            sleep 30
            # Optional: Add a check to verify services are running
            docker compose ps